import { pdfjsLib, DEFAULT_PDF_OPTIONS } from '@/utils/pdfjs'
import { readFileAsArrayBuffer } from '@/utils/fileUtils'

/**
 * Convert a canvas to a PNG data URL
 */
function canvasToDataUrl(canvas: HTMLCanvasElement): string {
  return canvas.toDataURL('image/png')
}

/**
 * Convert PDF to a single SVG embedding all pages as images.
 * Renders each page to canvas, then embeds them as <image> elements stacked vertically.
 */
export async function pdfToSvg(
  file: File,
  dpi: number = 150,
  onProgress?: (percent: number) => void
): Promise<{ svg: string; totalPages: number }> {
  onProgress?.(10)
  const buffer = await readFileAsArrayBuffer(file)

  onProgress?.(20)
  const loadingTask = pdfjsLib.getDocument({ data: buffer, ...DEFAULT_PDF_OPTIONS })
  const pdf = await loadingTask.promise
  const totalPages = pdf.numPages
  const scale = dpi / 72

  const pageImages: Array<{ dataUrl: string; width: number; height: number }> = []

  for (let i = 1; i <= totalPages; i++) {
    onProgress?.(20 + Math.round((i / totalPages) * 70))
    const page = await pdf.getPage(i)
    const viewport = page.getViewport({ scale })
    const canvas = document.createElement('canvas')
    canvas.width = Math.floor(viewport.width)
    canvas.height = Math.floor(viewport.height)

    // Ensure valid dimensions
    if (canvas.width <= 0) canvas.width = 1
    if (canvas.height <= 0) canvas.height = 1

    const ctx = canvas.getContext('2d')
    if (!ctx) throw new Error('Cannot get canvas 2D context')

    ctx.fillStyle = '#ffffff'
    ctx.fillRect(0, 0, canvas.width, canvas.height)

    await page.render({ canvas, canvasContext: ctx, viewport }).promise

    const dataUrl = canvasToDataUrl(canvas)
    pageImages.push({ dataUrl, width: canvas.width, height: canvas.height })
  }

  // Build single SVG with all pages stacked vertically
  const maxWidth = Math.max(...pageImages.map((p) => p.width), 1)
  let totalHeight = 0
  const gap = 4 // small gap between pages

  const imageElements: string[] = []
  for (const page of pageImages) {
    const x = Math.round((maxWidth - page.width) / 2) // center horizontally
    imageElements.push(
      `<image x="${x}" y="${totalHeight}" width="${page.width}" height="${page.height}" href="${page.dataUrl}"/>`
    )
    totalHeight += page.height + gap
  }
  totalHeight -= gap // remove last gap

  const svg = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"`,
    `  width="${maxWidth}" height="${totalHeight}"`,
    `  viewBox="0 0 ${maxWidth} ${totalHeight}" version="1.1">`,
    `  <!-- Generated by PDF Elf — ${totalPages} page(s) -->`,
    `  ${imageElements.join('\n  ')}`,
    `</svg>`,
  ].join('\n')

  onProgress?.(100)
  return { svg, totalPages }
}

/**
 * Generate an SVG Blob from SVG string
 */
export function svgToBlob(svg: string): Blob {
  return new Blob([svg], { type: 'image/svg+xml;charset=utf-8' })
}
